# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'

target 'zhihuDaily' do
pod 'AFNetworking'
pod "SDWebImage"
pod "MJExtension"
pod "DKNightVersion"
pod "SDCycleScrollView"
end
